### PR TITLE
Add logging via Winston

### PR DESCRIPTION
**Pull request by derjust**
To allow for easier debugging & auditing adding logging to the crucial code paths.

Leveraging Winston to be flexible about the actual logging backend.
Having Winston-Splunk as dependency to allow for easy - but optional - logging to Splunk right away (especially for AWS-Lambda deployment)

### CODE REVIEW

**Comment by TimothyJones** [comment]
This is awesome, thanks very much for this! 

Would you be able to add to the readme to explain the logging / configuration, please?

**Comment by derjust** [comment]
@TimothyJones , i added a new commit to the branch/this PR to clarify.

**Comment by TimothyJones** [comment]
Thanks! Also, after a closer read of the logging, I'm wondering if the tokens and codes should be logged, since they can be sensitive?

Should those lines be debugs? (I'm happy to make those changes)

**Comment by derjust** [comment]
Updated the PR to hide sensitive information on debug level (or not log at all)

**Comment by TimothyJones** [comment]
Thanks for this!

**Comment by TimothyJones** [comment]
I've merged it in, much appreciated.

I hope you don't mind, I went and moved a few more of the info statements to debug - my thinking is that nothing that belongs to any users needs to be logged during normal operation. Happy to discuss if you think there's a better default behaviour.

**Pull request merged**
