### PR TITLE
Adding a new deployment option using CDK

### PR DESCRIPTION
**Pull request by ChristopheBougere**
Thanks for the great wrapper.

As I am already using CDK everywhere in my app, thus I created a CDK construct that is available [here](https://github.com/scenario-labs/user-pool-identity-provider-github). I am basically vendoring the compiled lambda code from this repo (see the [vendoring script](https://github.com/scenario-labs/user-pool-identity-provider-github/blob/main/scripts/bump-github-cognito-openid-wrapper.sh)), and distributing it as a CDK construct.

This PR references the construct in the README as a 3rd deployment option.

Note that my first idea was to implement the construct directly in this repo. However, to make a good construct it is advised to use [projen](https://github.com/projen/projen), a project generator that handles all the configuration of the project, including building, testing, publishing packages to various package managers. It seems to be that it would have been too many changes to this repo that might have been in conflict with the two current deployment options, and I thought it was wiser to make it independent.

### CODE REVIEW

**Comment by TimothyJones** [comment]
This is nice work! Thank you.

I occasionally get questions about adding the option to deploy using non-native cloudformation (serverless / CDK etc), and I haven't really hit on a good way to integrate them, and it's hard to maintain deployment frameworks that I don't know too much about. I think your solution of a separate project is a sensible one (and perhaps I should have done that for SAM in the first place).

A few quick thoughts:

* I like the instructions that you've added to the readme. Should those also be in the readme for the CDK project, too?
* I wonder if the npm module would be better named `user-pool-identity-provider-github-cdk` ?
* It's possible that the API for the construct might migrate but this readme wouldn't be updated. I'm not sure how best to mitigate this risk (a reminder comment in the API file, maybe?)
* Is there a way to check that the deployment is the same as the original SAM templates? The CDK documentation suggests that we might be able to use `cdk diff`

A couple of tasks for me:

* I'll add a note to the readme crediting you more explicitly for the CDK construct
* I noticed that the vendoring script could be a bit more robust - I'll shoot you a PR

**Comment by TimothyJones** [comment]
Ah - there's potentially a major problem in that vendoring the package publishes the private key used to verify tokens (it's bundled in the deployable). I'm not sure what the best fix is- probably putting the private key in an SSM parameter or something?

**Comment by ChristopheBougere** [comment]
Thanks for the great review :)

- I've been a bit eager to integrate it and neglected the readme, I'll work on that so if people first discover the CDK construct they have enough information to deploy it.
- You're right, I don't see any naming convention yet but I will add `cdk` or `cdk-construct` in the name to make things clear. I won't be able to remove the current package from npm though (but I can deprecate it).
- You're right about the construct API, for instance, the attribute mapping could be passed as an option. I might add all the instructions in the construct readme, and simply redirect people from here.
- Do you mean a way to check it right now, or a way to integrate it in the CI? For the first case, sure I can post a generated CF stack. By the way, I am checking the presence of some resources in [the tests](https://github.com/scenario-labs/user-pool-identity-provider-github/blob/main/test/user-pool-identity-provider-github.test.ts#L39). However, comparing SAM template and CDK generated CF stack in the CI won't work well in my opinion/

Very good call for the private key, thanks. SSM would be a solution. Another one would be to generate it in the CDK construct (so at deploy time). That would require changing the webpack config so the key is bundled in a separate file and we can override it in the construct.

**Comment by ChristopheBougere** [comment]
Hi @TimothyJones,

- I've renamed the project to [cdk-user-pool-identity-provider-github](https://github.com/scenario-labs/cdk-user-pool-identity-provider-github)
- Instead of providing setup/deployment instructions in this readme, I've added a full setup tutorial in the construct readme, and I linked to it.

I think we should address the security concern before merging though.
Do you think we could configure webpack so it doesn't bundle the `jwtRS256.key` and `jwtRS256.key.pub` ([used here](https://github.com/TimothyJones/github-cognito-openid-wrapper/blob/master/src/crypto.js#L7)), so we can add them later?

**Comment by TimothyJones** [comment]
Yes, absolutely. Another approach could be to get it to load the keys from
(say) SSM.

**Comment by ChristopheBougere** [comment]
Ideally, I would prefer to keep it simple for the user and avoid adding extra steps (like manually specifying keys in SSM).

I've updated the webpack config in [this commit](https://github.com/TimothyJones/github-cognito-openid-wrapper/pull/62/commits/053b0780cf1dd776ea54c7b6039806983f76ebfe), to copy the jwtRS256.key and jwtRS256.key.pub files instead of bundling them. They are read using `fs.readFileSync()` instead of `require()`.

If that works for you, I will update the `cdk-user-pool-identity-provider-github` script so it removes the keys before vendoring the code. Then, I will implement the key generation in the construct at deploy time.

**Comment by ChristopheBougere** [comment]
I am actually trying a new approach in [this PR](https://github.com/scenario-labs/cdk-user-pool-identity-provider-github/pull/4/files).
Instead of vendoring `github-cognito-openid-wrapper`, I build it in a docker container directly with CDK (see the [Dockerfile](https://github.com/scenario-labs/cdk-user-pool-identity-provider-github/pull/4/files#diff-f7c91877446336ef59ebfaacb472e50e4e40bbe54938f232b0fd54617eb6e7dc), and its [usage](https://github.com/scenario-labs/cdk-user-pool-identity-provider-github/pull/4/files#diff-6ce1f38aa32cfa9a0a78874665c469df8a5f33c0f482edd22c136616f051e28dR52)).

If that works well (ie it doesn't need to be rebuilt on every deploy), that might be the best solution.

**Comment by ChristopheBougere** [comment]
The approach I describe in my previous comment looks pretty good. Additionally, it doesn't require any change from this repo. I've just updated the readme to point to the construct repo.

Let me know what you think @TimothyJones

**Comment by TimothyJones** [comment]
Hi there! Sorry for the delay - I've lost some of the context here. Can you remind me what the status of this PR is?

A cursory skim read of your repo looks like this one might be ready to merge.

**Comment by ChristopheBougere** [comment]
Hi @TimothyJones 
So we ended up not using Cognito with Github, and we cannot maintain the construct without using it.
I've updated the readme and archived the repo.
I think it could still help some CDK users out there. I've updated the PR to only let a simple reference about it, let me know what you think

**Comment by TimothyJones** [comment]
Looks great, thank you!

**Pull request merged**
