### PR TITLE
GitHub Enterprise support

### LINKED ISSUE #14: Autodiscovery issue
I fixed the issue with the autodiscovery by moving the `jwks.json` endpoint into the `/.well-known` path, similar to the OpenIdDiscovery endpoint.

### PR DESCRIPTION
**Pull request by derjust**
This PR is to add support for GitHub Enterprise by letting the `github.com` URL to be configurable and remove hardcoded URLs from the code base.

Testcases have been added for this, too.

Also some minor issue where fixed along the way, each in its own commit:
* Properly generate the key on OSX 10.14
* Fix #14 as per the issue
* Discover the `stage name` in a Lambda deployment
* Update dependencies to solve known issues (`npm audit`)

### CODE REVIEW

**Comment by TimothyJones** [comment]
Thanks very much for this!

Could you comment a bit on the key generation issue? I developed this on OSX 10.14, and didn't have any problems.

**Comment by TimothyJones** [comment]
On small comment - In the commit message, you link the Auth0 documentation to show the default location for jwks is at `/.well-known/`. I believe that's the documentation for the Auth0 product, and not the OpenID spec. Although much of the information is the same, the Auth0 docs shouldn't be a source for implementers. 

As far as I am aware, this isn't defined by any relevant standard or RFC, and so I think it's a Cogntio bug not to use the URL returned by the discovery endpoint.

However, since we know what the issue is (and most implementations put the jwks uri under `/.well-known/` anyway) we should still fix it - and the PR is very much appreciated.

**Comment by derjust** [comment]
> so I think it's a Cogntio bug not to use the URL returned by the discovery endpoint.
Yes I think you are right - the Auth0 was just the only resource I could find 'as reference'.
But yes, everything you said :-)

**Comment by derjust** [comment]
Without `-m PEM` it would fail in `crypto.js` with
```
crypto.js:331
  var ret = this._handle.sign(toBuf(key), passphrase, rsaPadding,
                         ^

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Sign.sign (crypto.js:331:26)
    at Object.sign (~/development/oss/github-cognito-openid-wrapper/node_modules/jwa/index.js:76:45)
    at Object.jwsSign [as sign] (~/development/oss/github-cognito-openid-wrapper/node_modules/jws/lib/sign-stream.js:32:24)
    at Object.module.exports [as sign] (~/development/oss/github-cognito-openid-wrapper/node_modules/jsonwebtoken/sign.js:188:16)
    at Object.makeIdToken (~/development/oss/github-cognito-openid-wrapper/src/crypto.js:26:16)
...
```
(Note: The lines might be a little bit off as I added a ton of debug logging not included in the PR)

The offending key:
```
$ file jwtRS256.key 
jwtRS256.key: OpenSSH private key
```

The working key (with `-m PEM` as per 9d857c3):
```
$ file jwtRS256.key
jwtRS256.key: PEM RSA private key
```

My software versions:
```
$ ssh -v localhost
OpenSSH_7.9p1, LibreSSL 2.7.3
```
```
$ openssl version
LibreSSL 2.6.5
```
```
$ node --version
v8.16.0
```

**Comment by TimothyJones** [comment]
Thanks again for this!

**Pull request merged**
