### PR TITLE
Serverless framework, debug messages and make issuer more dynamic

### PR DESCRIPTION
**Pull request by tcchau**
I haven't done a pull request in some time, so I hope the procedure is correct.

The goal of my changes was to get this wrapper/adapter working under Serverless. 

Along the way, I put in some debug-level logging that you can turn on by using Serverless' SLS_DEBUG environment flag, and I also changed the ```getIssuer()``` logic to be more dynamic so that it can handle custom domains defined in API Gateway

### CODE REVIEW

**Comment by TimothyJones** [comment]
This is much appreciated, thank you! I'll take a closer look soon.

It would be nice to have a logging pattern that works irrespective of how it's deployed - do you have any thoughts on this?

**Comment by tcchau** [comment]
> It would be nice to have a logging pattern that works irrespective of how it's deployed - do you have any thoughts on this?

Hi, @TimothyJones. Something I do in my own projects is to actually set a process environment variable to flag whatever condition I want, and these are set irrespective of deployment methodology. 

I do agree, the SLS_DEBUG is of course, very Serverless-specific as a convention. Let me know if you want it revised to use environment variables instead.

**Comment by TimothyJones** [comment]
Sorry for the slow response. I'd like to accept this, but I think a more generic approach to logging is probably better long term. What do you think of the approach in #19 ?

**Comment by TimothyJones** [comment]
One approach could be to update this PR to not include the logging changes, then merge both PRs, then have a subsequent PR that allows the `SLS_DEBUG` to control the logging? If you have the time, of course.

**Comment by TimothyJones** [comment]
I'm going to close this for now. Master has diverged a bit since august, and there hasn't been any activity to make the logging controls less specific to serverless. Please feel free to reopen and amend if you'd still like this merged.

**Pull request closed without merging**
