### PR TITLE
fix reference error auth is not util/auth

### PR DESCRIPTION
**Pull request by deptno**
incorrect `auth.js` is required.

`util/auth.js` has `getIssuer ` function, not `auth.js`

### CODE REVIEW

**Comment by TimothyJones** [comment]
Thanks for this! This change will actually provide the wrong discovery URL, because the one from the lambda has `/Prod` appended to it. 

However, you're right that the `auth` in the web folder doesn't expose the right interface. I'll correct this.

**Comment by TimothyJones** [comment]
Thanks for this! This change will actually provide the wrong discovery URL, because the one from the lambda has `/Prod` appended to it. 

However, you're right that the `auth` in the web folder doesn't expose the right interface. I'll correct this.

**Comment by TimothyJones** [comment]
Thanks for this! This change will actually provide the wrong discovery URL, because the one from the lambda has `/Prod` appended to it. 

However, you're right that the `auth` in the web folder doesn't expose the right interface. I'll correct this.

**Comment by TimothyJones** [comment]
Thanks for this! This change will actually provide the wrong discovery URL, because the one from the lambda has `/Prod` appended to it. 

However, you're right that the `auth` in the web folder doesn't expose the right interface. I'll correct this.

**Comment by TimothyJones** [comment]
Thanks for this! This isn't quite the right fix, because `${host}/Prod` isn't the right URL for the web version.

However, you're right to point out that `getIssuer` was missing from `auth.js`. I've fixed this in d098a43.

**Comment by TimothyJones** [comment]
Hm. Sorry for the spam. GitHub is a bit unstable today.

**Comment by deptno** [comment]
Alright. Thanks 😄

**Pull request closed without merging**
